// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: image.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	UploadImage(ctx context.Context, in *ImageMessage, opts ...grpc.CallOption) (*ImageURL, error)
	UploadMultipleImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_UploadMultipleImageClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) UploadImage(ctx context.Context, in *ImageMessage, opts ...grpc.CallOption) (*ImageURL, error) {
	out := new(ImageURL)
	err := c.cc.Invoke(ctx, "/store.internal.pb.ImageService/UploadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) UploadMultipleImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_UploadMultipleImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImageService_ServiceDesc.Streams[0], "/store.internal.pb.ImageService/UploadMultipleImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceUploadMultipleImageClient{stream}
	return x, nil
}

type ImageService_UploadMultipleImageClient interface {
	Send(*ImageMessage) error
	Recv() (*ImageURL, error)
	grpc.ClientStream
}

type imageServiceUploadMultipleImageClient struct {
	grpc.ClientStream
}

func (x *imageServiceUploadMultipleImageClient) Send(m *ImageMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageServiceUploadMultipleImageClient) Recv() (*ImageURL, error) {
	m := new(ImageURL)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	UploadImage(context.Context, *ImageMessage) (*ImageURL, error)
	UploadMultipleImage(ImageService_UploadMultipleImageServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) UploadImage(context.Context, *ImageMessage) (*ImageURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImageServiceServer) UploadMultipleImage(ImageService_UploadMultipleImageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMultipleImage not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.internal.pb.ImageService/UploadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).UploadImage(ctx, req.(*ImageMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_UploadMultipleImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).UploadMultipleImage(&imageServiceUploadMultipleImageServer{stream})
}

type ImageService_UploadMultipleImageServer interface {
	Send(*ImageURL) error
	Recv() (*ImageMessage, error)
	grpc.ServerStream
}

type imageServiceUploadMultipleImageServer struct {
	grpc.ServerStream
}

func (x *imageServiceUploadMultipleImageServer) Send(m *ImageURL) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageServiceUploadMultipleImageServer) Recv() (*ImageMessage, error) {
	m := new(ImageMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.internal.pb.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadImage",
			Handler:    _ImageService_UploadImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMultipleImage",
			Handler:       _ImageService_UploadMultipleImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "image.proto",
}
